### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by ToggleIP** [tuz1k/caseopening#1]
Hi,

I still get this issue but i cannot find what it is. Please help me.

http://prntscr.com/hwymkn

**Comment by tuz1k** [comment]
In js folder there is file called "base.js" change line 4 to your domain and enable ssl

**Comment by ToggleIP** [comment]
I have changed it but it still shows up

**Comment by ToggleIP** [comment]
now it says this 
![image](https://user-images.githubusercontent.com/29839005/34650238-fc428492-f3bd-11e7-959e-614ee12c2415.png)

**Comment by ToggleIP** [comment]
now it says 

Failed to load resource: the server responded with a status of 521 ()
mydomain/:1 

Failed to load https://mydomain:8443/socket.io/?EIO=3&transport=polling&t=M3G-zCe: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mydomain' is therefore not allowed access. The response had HTTP status code

**Comment by tuz1k** [comment]
without slash and the end

**Comment by ToggleIP** [comment]
Hey. I have it like this http://prntscr.com/hx7y39 without slash at the end but still shows up
